### ISSUE TITLE
[Discord] Empty Embeds 

### ISSUE THREAD

**Issue by LegitDongo** [pokealarm/pokealarm#517] opened 2017-12-15 01:09 UTC
## Troubleshooting Checklist

- [x] My RocketMap install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description
On particular monsters (Girafarig, Bayleef, and now possibly Vigoroth and Clefairy), the embed simply will not be there when the notification is sent to Discord.
Upon further looking at the debug info and usages with the webhook tester, everything looks appropriate and should send appropriately.
The content of the message will still appear like normal.

## Environment
Operating System: N/A  
Python Version: 2.7
PokeAlarm Branch: master
PokeAlarm Version: latest

## PokeAlarm Setup:
Your config file: see users
Your filters file: see users
Your alarms file:  see users

## Log Output
Logs are complete and have no errors

**Comment by boby361** [comment] 2017-12-15 02:32
i run 2 servers in 1 VM on lubuntu. They both have the exact filter and exact alarm (except different webhook) the only pokemon i have noticed not go through is Vigoroth. on one of the two servers.
https://pastebin.com/bBH0tJEH - filter
https://pastebin.com/wjWw0cnv - alarm
https://pastebin.com/MUCJ9wg1 - config

debug logs don't get a 402 (successfuly received code) from what i saw.

**Comment by dongemus** [comment] 2017-12-15 03:09
I run on windows. Same things happen to me, not every time but often,
Bayleef is the worst for me. Looking through logs I can't find anything,
Nothing different in the filters.

**Comment by kvangent** [comment] 2017-12-15 03:59
Here is what we have discovered:
1. It's only on certain servers (setups that only switch the webhook url start working)
2. It's image related - using a different image works
3. It's specific to certain images - changing the url to the same image doesn't seem to help

So it's almost certainly on Discord's end, but we may be able to fix the images to no longer have this issue.

**Comment by blsmit5728** [comment] 2017-12-15 12:01
My problem just started on Vigoroth, but has been plaguing me for months with Girafarig. 
Config: [(https://pastebin.com/3f65Ud67)]
Filters: [https://pastebin.com/Y4gSPW2j]
Alarms: [https://pastebin.com/PbpiCxsd]

I spent a couple days once Girafarig was doing it to even get exactly what is sent to Discord in a dump, lay it out in a CURL command and send it to multiple webhooks. Just one single webhook was showing the issue the others would post just fine.

**Comment by geekygreek7** [comment] 2017-12-17 05:14
First bayleef, then clefairy, not Vigoroth. (windows 10 here). Did alarm test tool too

**Comment by sLoPPydrive** [comment] 2017-12-19 09:31
Is there at least a glimpse of an idea what causes this issue?

**Comment by kvangent** [comment] 2017-12-19 13:18
@sLoPPydrive As I said above, it's image related - only certain images cause it. But it's also discord server related - only certain discord servers have this problem. The exact same webhook will work on my server but not on someone else. So the problem is certainly an issue on Discord's end that's erroring out on certain images, but not for all servers.

The short term workaround for this is to just use different images.

**Comment by LegitDongo** [comment] 2018-01-15 16:14
Found this issue to persist into 3.5

**Comment by kvangent** [comment] 2018-03-18 16:01
Received a response from discord:
```
Hi PokeAlarm Team,

Thanks so much for reaching out to us! Currently the team is aware about this issue with embeds posted by bots, and is working on a fix for this in a future update! I sadly don't have an exact ETA for when a solution will be available, so I'm so sorry for all the inconvenience and hassle.

In the meantime though, please let me know if you have any questions or need anything else!

Sincerely,
Nimbus‍
```

**Comment by billyjbryant** [comment] 2022-05-24 18:43
@LegitDongo do you know if this is still an issue?

**Comment by LegitDongo** [comment] 2022-05-24 18:44
I haven't heard anything on this since 2018

**Comment by billyjbryant** [comment] 2022-05-24 19:13
Closing this issue.

**Closed by billyjbryant** 2022-05-24 19:13 UTC
Labels: type: bug
