### ISSUE TITLE
[ENHANCEMENT] Re-Reading Configuration Files Upon Notification

### ISSUE THREAD

**Issue by aeble** [PokeAlarm/PokeAlarm#419] opened 2017-08-07 10:12 UTC
## Your Environment
!--- Please post as many details  --
OS: irrelevant
Python version: irrelevant
RocketMap and PokeAlarm startup command line: irrelevant

!--- [ENHANCEMENT] Use this template if you have a suggestion for improving PokeAlarm   -----
## Enhancement Description
!--- Please describe the improvement you are proposing.  --
Ability to reload config files (like upon receiving a SIGUSR1 or SIGHUP)

## Use cases
!--- Please describe why you think this improvement will be useful --
Changed configuration shouldn't really require a restart of the process. A notification to reload would suffice plenty. 

## Other Links
!--- If you are suggesting a new service, please include a link to relevant API or Python module --

!--- END OF [ENHANCEMENT] TEMPLATE  ---------------------------------------------------------------

**Comment by kvangent** [comment] 2017-11-08 03:54
Closing this because it's pretty much covered by FileCache.

**Closed by kvangent** 2017-11-08 03:54 UTC
Labels: feature request

**Comment by wickles** [comment] 2018-01-16 20:19
How is this covered? As far as I can tell, it still requires restarting to reload the configuration files (alarms, filters, etc.)

**Comment by kvangent** [comment] 2018-01-16 23:36
@wickles I believe when I closed this at the time, it was because shutting down and starting up PA can be done without any loss in service. PA stops receiving new requests and finishes processing any queued before closing, and it also dumps it's current state into the filecache (with the exception of the reverse geocoding cache).

**Comment by wickles** [comment] 2018-01-17 01:04
The problem is that PA will miss any webhooks sent during the downtime. (Unless I misunderstand and it somehow receives these later?) And it's just frustrating to have to stop and restart for any changes. Probably a decent first pass would be a simple timed refresh like how RM reads proxy files.
